### ISSUE TITLE
How can I use this hbase reader?

### ISSUE THREAD

**Issue by yeyeya1008** [glefloch/spring-batch-hbase#1]
Can you give me some example using this hbase reader in Spring Batch Application?
I have no idea how can i set list of scan in hbase reader? where it from?
Please let me know more information How to use it. Thank you.

**Comment by glefloch** [comment]
Hi,

In order to use the Hbase Reader, you must create a mapper which implement the `Function<T, Result>` interface where T is the type of object you want to process and Result the result of the hbase `Scan`. 

Then in your job, you can create a reader bean from the reader class, here is an example using xml:

	<bean id="hbaseReaderExample" scope="step" class="org.springframework.batch.tasklet.item.reader.HbaseReader">
		<property name="hTemplate" ref="hTemplate" />
		<property name="tableName" value="ns:tablename"/>
		<property name="mapper">
			<bean scope="step" class="com.github.glefloch.SomeMapper"/>
		</property>
		<property name="scans" ref="someScans" />
	</bean>

The bean take the following parameters:

* `hTemplate`: template used to access Hbase
* `tableName`: name of the table to query
* `mapper`: class used to convert Hbase result into the desired type
* `scans`: list of Hbase scan to execute

I hope this helps!

**Comment by yeyeya1008** [comment]
@glefloch Great! Thank you so much!
